"""Set PK to UUID

Revision ID: aef20a20b6f2
Revises: 
Create Date: 2024-12-21 19:48:07.765505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef20a20b6f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('places',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('place_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('place_name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_start', sa.String(), nullable=False),
    sa.Column('date_end', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('logo_width', sa.Integer(), nullable=False),
    sa.Column('logo_height', sa.Integer(), nullable=False),
    sa.Column('small_logo', sa.String(), nullable=False),
    sa.Column('small_logo_width', sa.Integer(), nullable=False),
    sa.Column('small_logo_height', sa.Integer(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('age_restriction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('events_places',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_places')
    op.drop_table('events')
    op.drop_table('places')
    op.drop_table('categories')
    # ### end Alembic commands ###
