"""Initial sqlite edited

Revision ID: b26072f3e874
Revises: bd3399f218fc
Create Date: 2024-12-18 14:07:44.392884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26072f3e874'
down_revision: Union[str, None] = 'bd3399f218fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_places',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'place_id')
    )
    op.drop_table('events-places')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events-places',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'place_id')
    )
    op.drop_table('events_places')
    # ### end Alembic commands ###
